### ISSUE TITLE
Mention in Turbo Vision's main page

### ISSUE THREAD

**Issue by magiblot** [electroly/tmbasic#1]
Hi Brian, 

I'm happy to see someone is taking advantage of [tvision](https://github.com/magiblot/tvision) seriously.

Would you mind if I mentioned your project in Turbo Vision's main page?

Cheers.

**Comment by electroly** [comment]
Hi there! I'd be happy to have that mention. I'm still in the relatively early stages of development, but I hope to ship a programming environment where BASIC programmers can easily create tvision-based interfaces without needing to learn C++. The discovery of your excellent port was the direct inspiration for this project -- thanks for your good work!

I may have some fixes I can try to upstream if you're interested. In particular I have a minor fix to allow the port to build on ARM64, and additionally some fixes to allow it to build with the outdated macOS 10.13 Xcode install that [Macincloud](https://www.macincloud.com/) uses.

**Comment by magiblot** [comment]
You are welcome. You can submit a pull request, but it's enough if you point me to the fixes in your code.

Likewise, I can help you upgrade to the latest upstream version.

Cheers.
