### ISSUE TITLE
How to compile and which compiler.?

### ISSUE THREAD

**Issue by Spoiledpay** [electroly/tmbasic#6]
Dear, how can we compile a version for windows? thanks

**Comment by magiblot** [comment]
From what I can gather, there are build scripts that are probably meant to be run on Linux which generate Windows binaries from within a Docker container.

For example, from this repository's root:

```sh
cd build
./win-x64.sh
```

Then you will be dropped into a shell inside the Docker container from which you can run `make tmbasic`, and tmbasic will be built.

**Comment by electroly** [comment]
Hi @Spoiledpay, sorry for the delayed response. @magiblot is right; tmbasic only supports cross-compiling Windows builds from Linux. This is admittedly not great for Windows developers. You may prefer to wait until tmbasic is ready for release and then use a prebuilt binary. But if you want to brave the prerelease code, I have build instructions here: https://github.com/electroly/tmbasic/blob/master/doc/building-from-source.md

**Comment by marioroy** [comment]
Thank you for tmbasic.

Instructions for building tmbasic moved.
https://github.com/tmbasic-lang/tmbasic/blob/master/CONTRIBUTING.md
