### ISSUE TITLE
error when I did make release in macOS Monterey 12.3

### ISSUE THREAD

**Issue by juanmiuk** [electroly/tmbasic#7]
src/vm/Interpreter.cpp:518:23: error: unused variable 'frame' [-Werror,-Wunused-variable]
                auto& frame = _private->callStack.top();
                      ^
             c++  obj/compiler/fixDottedExpressionFunctionCalls.o
             c++  obj/compiler/ast.o
             c++  obj/compiler/parse.o
1 error generated.
make[1]: *** [obj/vm/Interpreter.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [release] Error 2

**Comment by electroly** [comment]
Hi @juanmiuk. I will take a look. I haven't built the macOS target in awhile; it often finds different problems than other compilers.

**Comment by electroly** [comment]
These issues should be addressed now. Please give it another try.

**Comment by juanmiuk** [comment]
Perfect!!, this time it's built perfectly. Thanks Mate!!. Ah!, sorry to writing  wrong the username on the before email, it was the automatic corrector fault!.
Thanks for you time.

CuriousAutistic (juanmiuk)
